name: Call Reusable Workflow

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - main
      - dev
    types: 
      - closed  

jobs:
  invoke-reusable-workflow:
    uses: AthivaTechnology/Reuseble-Pipeline/.github/workflows/sam-reusable.yml@main
    with:
      stack-name: quicksight-dashboard
      dev-config-env: default
      prod-config-env: prod